spring.profiles:
  active: local
  group:
    local: local, common, secret
    blue: blue, common, secret
    green: green, common, secret

server:
  env: blue

---
spring:
  config.activate.on-profile: local

server:
  port: 8080

---
spring:
  config.activate.on-profile: blue

server:
  port: 8080
  address: 0.0.0.0
---
spring:
  config.activate.on-profile: green

server:
  port: 8081
  address: 0.0.0.0
---

spring:
  config.activate.on-profile: common
  application.name: demo

# Swagger 공통 설정
springdoc:
  swagger-ui:
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.jolupbisang.demo
