apiVersion: 1

datasources:
  - name: Prometheus
    uid: silrok-prometheus
    type: prometheus
    access: proxy
    url: http://my-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s