name: ci

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # pr 요청한 브랜치 코드 내려 받기
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # 자바 다운로드 및 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 테스트를 위한 DB 설정
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{ secrets.MYSQL_TEST_DATABASE }}
          mysql user: ${{ secrets.MYSQL_TEST_USER }}
          mysql password: ${{ secrets.MYSQL_TEST_PASSWORD }}

      # Gradlew 실행 권한 설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # 테스트 없이 빌드
      - name: Build with test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test

