name: Deploy Docker Compose Files

on:
  push:
    branches:
      - develop
    paths:
      - 'docker/docker-compose*.yml'
      - 'docker/docker-compose*.yaml'

permissions:
  contents: read

jobs:
  deploy-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: make docker folder to EC2
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_USERNAME }}
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            mkdir -p ~/docker

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.EC2_USERNAME }}
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker/docker-compose*.yml,docker/docker-compose*.yaml"
          target: "~/"
          strip_components: 0

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.EC2_USERNAME }}
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            echo "Deployed docker-compose files:"
            cd docker
            stat -c '%n , %y' docker-compose*.yml 2>/dev/null || echo "No docker-compose files found"
